options:
  target_path:  decrypted.bin
  asm_path:     asm/cps3/sfiii3n
  src_path:     src/cps3
  ld_scripts_path: config/cps3
  syms_path: config/cps3
  decomp_empty_funcs: false
segments:
  - name: game
    type: code
    start: 0x00000000
    vram:  0x06000000
    subalign: 2
    subsegments:
      - start: 0x0
        type: data
        file: game
      - start: 0x400
        type: c
        file: game
      # work_init_zero
      - start: 0x0DBB32
        type: c
        file: game
      - start: 0x0DBB6C
        type: data
        file: game
      - start: 0x0dcd1a
        type: c
        file: game
      - start: 0x13bdfa
        type: data
        file: game
