name: Build (Windows)

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: windows-latest

        defaults:
          run:
            shell: msys2 {0}

        steps:
          - name: setup MSYS2
            uses: msys2/setup-msys2@v2
            with:
                update: true
                msystem: MINGW64
                install: make clang cmake mingw-w64-x86_64-sdl3 ninja

          - name: Checkout repository
            run: git config --global core.autocrlf input #apparently this mitigates an MSYS or GHA bug
            uses: actions/checkout@v4

          - name: Build for Windows
            run: make PLATFORM=windows 2>&1 | tee build.log

          - name: Upload build log
            if: always()
            uses: actions/upload-artifact@v4
            with:
                name: build-log
                path: build.log
