name: Build (Linux)

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: ubuntu:25.04

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Install dependencies
            run: |
                apt update
                apt install -y build-essential make cmake clang libsdl3-0 libsdl3-dev

          - name: Build for Linux
            run: |
                set -o pipefail
                make PLATFORM=linux 2>&1 | tee build.log
            shell: bash

          - name: Upload build log
            if: always()
            uses: actions/upload-artifact@v4
            with:
                name: build-log
                path: build.log
